general {
    before_sleep_cmd = playerctl -a pause
    after_sleep_cmd = hyprctl dispatch dpms on
	lock_cmd = playerctl -a pause ; ambxst lock
#	unlock_cmd = playerctl -a play
}

listener {
    timeout = 200
    on-timeout = $HOME/.config/hypr/scripts/brightness-dim.sh
    on-resume = $HOME/.config/hypr/scripts/brightness-restore.sh
}

listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off & loginctl lock-session
    on-resume = hyprctl dispatch dpms on
}

listener {
	timeout = 900
	on-timeout = systemctl hibernate
}
